services:
  wg-easy:
    build:
      dockerfile: ./Dockerfile
    command: npm run serve
    volumes:
      - ./src/:/app/
      # - ./data/:/etc/wireguard
    ports:
      - "51830:51830/udp"
      - "51831:51831/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      # - PASSWORD_HASH=p
      - WG_HOST=192.168.1.233
